name: IMAGEN
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2022.10.11
  - certifi=2022.12.7
  - ld_impl_linux-64=2.38
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.3
  - openssl=1.1.1s
  - pip=22.3.1
  - python=3.8.15
  - readline=8.2
  - setuptools=65.6.3
  - sqlite=3.40.1
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.8
  - zlib=1.2.13
  - pip:
    - absl-py==1.4.0
    - accelerate==0.15.0
    - aiohttp==3.8.3
    - aiosignal==1.3.1
    - async-timeout==4.0.2
    - attrs==22.2.0
    - beartype==0.11.0
    - blessed==1.19.1
    - boto3==1.26.49
    - botocore==1.29.49
    - cachetools==5.2.1
    - chardet==3.0.4
    - charset-normalizer==2.1.1
    - click==8.1.3
    - datasets==2.8.0
    - dill==0.3.6
    - einops==0.6.0
    - einops-exts==0.0.4
    - ema-pytorch==0.1.4
    - filelock==3.9.0
    - frozenlist==1.3.3
    - fsspec==2022.11.0
    - google-auth==2.16.0
    - google-auth-oauthlib==0.4.6
    - gpustat==1.0.0
    - grpcio==1.51.1
    - huggingface-hub==0.11.1
    - idna==3.4
    - importlib-metadata==6.0.0
    - jmespath==1.0.1
    - joblib==1.2.0
    - kornia==0.6.9
    - lightning-utilities==0.5.0
    - markdown==3.4.1
    - markupsafe==2.1.1
    - multidict==4.7.6
    - multiprocess==0.70.14
    - numpy==1.24.1
    - nvidia-ml-py==11.495.46
    - oauthlib==3.2.2
    - packaging==23.0
    - pandas==1.5.2
    - pillow==9.4.0
    - protobuf==3.20.1
    - psutil==5.9.4
    - pyarrow==10.0.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==1.10.4
    - python-dateutil==2.8.2
    - pytorch-lightning==1.9.0rc0
    - pytorch-transformers==1.2.0
    - pytorch-warmup==0.1.1
    - pytz==2022.7
    - pyyaml==6.0
    - regex==2022.10.31
    - requests==2.28.2
    - requests-oauthlib==1.3.1
    - responses==0.18.0
    - rsa==4.9
    - s3transfer==0.6.0
    - sacremoses==0.0.53
    - sentencepiece==0.1.97
    - six==1.16.0
    - tensorboard==2.11.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5.1
    - tokenizers==0.13.2
    - torch==1.12.1+cu113
    - torchmetrics==0.11.0
    - torchvision==0.13.1+cu113
    - tqdm==4.64.1
    - transformers==4.25.1
    - typing-extensions==4.4.0
    - urllib3==1.26.14
    - wcwidth==0.2.6
    - werkzeug==2.2.2
    - xxhash==3.2.0
    - yarl==1.8.2
    - zipp==3.11.0
